# .github/workflows/build.yml
name: Build (legacy + gradle)

on:
  push:
    branches: [ main, master, renovation/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  legacy-javac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Compile legacy sources
        run: |
          set -euo pipefail
          mkdir -p out
          # compile ONLY the legacy tree (you moved src/ under legacy/)
          find legacy/src/main/java -name "*.java" -print0 | xargs -0 javac -encoding UTF-8 -d out

  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build v2 modules (core/cli/analytics)
        run: |
          set -euo pipefail
          ./gradlew clean build

